# -*- coding: utf-8 -*-
"""B92 QKD Eavesdropped

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T2IF80F0TJdleHdEi-C2GqpeoNlQVOEV
"""

!pip install --upgrade cirq cirq-google numpy

import cirq
import cirq_google
import cirq_web
import numpy as np
import math
import scipy
import sympy
import random
import matplotlib.pyplot as plt
import sys
sys.meta_path[:] = [f for f in sys.meta_path if "DaskFinder" not in str(f)]
from math import radians, degrees
from scipy.optimize import minimize
from cirq_web import bloch_sphere
from cirq import Z, PauliSum

def run_B92(repetitions, eavesdropper_active=False):
  alice_key = []
  bob_key = []
  loops = 0

  while len(alice_key) < repetitions:
    loops += 1
    q = cirq.NamedQubit("q")
    simulator = cirq.Simulator()

    alice_bit = random.choice([0, 1])

    circuit = cirq.Circuit()
    if alice_bit == 1:
      circuit.append(cirq.X(q))
      circuit.append(cirq.H(q))

    # --- Eavesdropper's action ---
    if eavesdropper_active:
      eve_basis = random.choice(['Z', 'X'])
      # Eve measures the qubit in her chosen random basis, collapsing its state.
      if eve_basis == 'Z':
        circuit.append(cirq.measure(q, key='eve_m_z')) # Measure in Z
      else: # eve_basis == 'X'
        circuit.append(cirq.H(q)) # Rotate to X basis
        circuit.append(cirq.measure(q, key='eve_m_x')) # Measure in X
        circuit.append(cirq.H(q)) # Rotate back to Z basis (optional for Eve to hide)

    bob_basis = random.choice(['Z', 'X'])

    # Bob's measurement and key generation for B92
    # Bob keeps a bit if his measurement basis is orthogonal to Alice's preparation basis.
    # For B92: Alice prepares |0> (Z-basis) or |+> (X-basis)
    #          Bob measures in X-basis if Alice sent |0> AND Bob wants to record 0.
    #          Bob measures in Z-basis if Alice sent |+> AND Bob wants to record 1.

    if bob_basis == 'X' and alice_bit == 0: # Alice sent |0> (Z-basis), Bob measures X-basis
        circuit.append(cirq.H(q)) # Rotate to X basis
        circuit.append(cirq.measure(q, key='mm'))
        result = simulator.run(circuit, repetitions=1)
        measurement = result.measurements['mm'][0][0]
        # Bob records his measurement. Alice's corresponding bit is her original alice_bit.
        alice_key.append(alice_bit)
        bob_key.append(measurement)

    elif bob_basis == 'Z' and alice_bit == 1: # Alice sent |+> (X-basis), Bob measures Z-basis
        circuit.append(cirq.measure(q, key = 'mm')) # Already in Z basis
        result = simulator.run(circuit, repetitions=1)
        measurement = result.measurements['mm'][0][0]
        # Bob records his measurement. Alice's corresponding bit is her original alice_bit.
        alice_key.append(alice_bit)
        bob_key.append(measurement)

  print("B92 Iterations required to generate requested key length:")
  print(loops)
  print(f"\nAlice's generated key ({len(alice_key)} bits):")
  print(alice_key)
  print(f"Bob's generated key ({len(bob_key)} bits):")
  print(bob_key)

  mismatches = sum(1 for a, b in zip(alice_key, bob_key) if a != b)
  if mismatches == 0:
      print("\n[+] SUCCESS: Keys match perfectly!")
      if eavesdropper_active:
          print("No eavesdropper detected (or Eve was extremely lucky/passive). This is unlikely with active eavesdropping.")
      else:
          print("No noise or eavesdropper detected.")
  else:
      print(f"\n[-] FAILURE: {mismatches} mismatches found between Alice's and Bob's keys.")
      print("Eavesdropper detected due to discrepancies in keys!")

  return alice_key, bob_key

# --- Scenario: With Eavesdropper, increased repetitions ---
print("\n--- Running B92 Protocol (With Eavesdropper, 100 repetitions) ---")
alice_key_with_eve_100, bob_key_with_eve_100 = run_B92(repetitions=100, eavesdropper_active=True)