# -*- coding: utf-8 -*-
"""Bitflip Noise

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CV8DryAhsr41IfYr88UcWBHVrqjVsOxM
"""

!pip install --upgrade cirq cirq-google numpy

try:
  import cirq
except ImportError:
  print ("installing cirq...")
  !pip install --quiet cirq
  print("installed cirq.")
  import cirq

import cirq_google
import cirq_web
import numpy as np
import math
import scipy
import sympy
import random
import matplotlib.pyplot as plt
import sys
sys.meta_path[:] = [f for f in sys.meta_path if "DaskFinder" not in str(f)]
from math import radians, degrees
from scipy.optimize import minimize
from cirq_web import bloch_sphere
from cirq import Z, PauliSum

import sys
sys.meta_path[:] = [f for f in sys.meta_path if "DaskFinder" not in str(f)]

noise = cirq.bit_flip(0.05) #Change 0.05 to whatever decimal to change depolarization chance

simulator = cirq.Simulator()

result = simulator.run(circuit.with_noise(noise), repetitions=100) #Repetition number can be changed