# -*- coding: utf-8 -*-
"""Cirq.DensityMatrix

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/195HqZpWMaXFUZJpiTiapugGCcgJzup_U
"""


import cirq

cirq.density_matrix(
    state: np.ndarray,
    qid_shape: (tuple[int, ...] | None) = None,
    *,
    copy: bool = False,
    validate: bool = True,
    dtype: (DTypeLike | None) = None,
    atol: float = 1e-07
    ) -> QuantumState