# -*- coding: utf-8 -*-
"""Cirq.Fidelity

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZAX3Xogywo-2D67oE9G_u6HeMfGWTJs5
"""


import cirq

cirq.fidelity(
    state1: cirq.QUANTUM_STATE_LIKE,
    state2: cirq.QUANTUM_STATE_LIKE,
    qid_shape: (tuple[int, ...] | None) = None,
    validate: bool = True,
    atol: float = 1e-07
    ) -> float