# -*- coding: utf-8 -*-
"""Depolarization Noise

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UkZam7KQZxs9aNv658PfJeNMG0yf6TXo
"""




import cirq
import cirq_google
import cirq_web
import numpy as np
import math
import scipy
import sympy
import random
import matplotlib.pyplot as plt
import sys
sys.meta_path[:] = [f for f in sys.meta_path if "DaskFinder" not in str(f)]
from math import radians, degrees
from scipy.optimize import minimize
from cirq_web import bloch_sphere
from cirq import Z, PauliSum

import sys
sys.meta_path[:] = [f for f in sys.meta_path if "DaskFinder" not in str(f)]

depolarize_noise = cirq.depolarize(0.11) #Change 0.05 to whatever decimal to change depolarization chance

simulator = cirq.Simulator()

result = simulator.run(circuit.with_noise(depolarize_noise), repetitions=100) #Repetition number can be changed
