# -*- coding: utf-8 -*-
"""fidelity

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y0mwWMMi7ksSUe1OKjvPocEqCir1yF9o
"""

!pip install cirq --quiet
import cirq

import cirq
import numpy as np

n_qubits = 3
qubits = cirq.LineQubit.range(n_qubits)

circuit = cirq.Circuit()
circuit.append(cirq.H(qubits[0]))
for i in range(n_qubits - 1):
    circuit.append(cirq.CNOT(qubits[i], qubits[i + 1]))

state_vector = cirq.final_state_vector(circuit)
state_matrix = np.outer(state_vector, np.conj(state_vector))
print("State Vector:", state_vector)

Pghzi= cirq.density_matrix(
    state = state_matrix,
    qid_shape = None,
    copy = False,
    validate= True,
    dtype = None,
    atol = 1e-07
    )
print("WITHOUT NOISE ")
print(Pghzi.density_matrix())


pghzi_matrix = Pghzi.density_matrix()
dim = 2**n_qubits
identity_matrix = np.identity(dim, dtype=pghzi_matrix.dtype)


PghzN_matrix = (1 - 0.11) * pghzi_matrix + (0.11 / dim) * identity_matrix


PghzN = cirq.density_matrix(state=PghzN_matrix, qid_shape=Pghzi.qid_shape)
print("WITH NOISE ")
print(PghzN.density_matrix())

state_vector_0 = np.array([1.0, 0.0], dtype=np.complex64)
state_matrix_0 = np.outer(state_vector_0, np.conj(state_vector_0))

Pb92i = cirq.density_matrix(
    state=state_matrix_0,
    qid_shape=(2,),
    copy=False,
    validate=True,
    dtype=np.complex64,
    atol=1e-07
)
print("WITHOUT NOISE ")
print(Pb92i.density_matrix())



print("WITH NOISE ")
pb92i_matrix = Pb92i.density_matrix()
dim_single_qubit = 2**1
identity_matrix_single_qubit = np.identity(dim_single_qubit, dtype=pb92i_matrix.dtype)


Pb92N_matrix = (1 - 0.05) * pb92i_matrix + (0.05 / dim_single_qubit) * identity_matrix_single_qubit


Pb92N = cirq.density_matrix(state=Pb92N_matrix, qid_shape=Pb92i.qid_shape)

print(Pb92N.density_matrix())

fidelity_ghz = cirq.fidelity(
    state1=Pghzi,
    state2=PghzN
)

fidelity_b92 = cirq.fidelity(
    state1=Pb92i,
    state2=Pb92N
)

total_fidelity = (fidelity_ghz ** 15) * (fidelity_b92 ** 15)

print(f"Total 60-Qubit System Fidelity: {total_fidelity:.4f}")

