# -*- coding: utf-8 -*-
"""GHZ Group: B92  QKD

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fO_T87kNkYiPgAODqohxq0053jeUqWoY
"""

!pip install cirq --quiet

import cirq
import random
my_qubits = []
for i in range (10):
  q = cirq.NamedQubit("q")
  simulator = cirq.Simulator()

  alice_bit = random.choice([0, 1])

  circuit = cirq.Circuit()
  if alice_bit == 1:
      circuit.append(cirq.X(q))
      circuit.append(cirq.H(q))

  bob_basis = random.choice(['Z', 'X'])
  if bob_basis == 'X' and alice_bit == 0:
      circuit.append(cirq.measure(q))
      result = simulator.run(circuit, repetitions=1)
      print(circuit)
      print(result)
      my_qubits.append(result)
      print(f"Alice's Secret Bit: {alice_bit}")
      print(f"Bob's Chosen Basis: {bob_basis}")
      print("-" * 30)
  elif bob_basis == 'Z' and alice_bit == 1:
      circuit.append(cirq.H(q))
      circuit.append(cirq.measure(q))
      result = simulator.run(circuit, repetitions=1)
      print(circuit)
      print(result)
      my_qubits.append(result)
      print(f"Alice's Secret Bit: {alice_bit}")
      print(f"Bob's Chosen Basis: {bob_basis}")
      print("-" * 30)
  else:
      circuit.append(cirq.measure(q))
      print("Discard")
      print("-" * 30)
my_qubits