# -*- coding: utf-8 -*-
"""GHZ QKD Eavesdropper

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xEUs67jjuspIv7j1eghlOgc51--Jezvd
"""

!pip install --upgrade cirq cirq-google numpy

import cirq
import cirq_google
import cirq_web
import numpy as np
import math
import scipy
import sympy
import random
import matplotlib.pyplot as plt
import sys
sys.meta_path[:] = [f for f in sys.meta_path if "DaskFinder" not in str(f)]
from math import radians, degrees
from scipy.optimize import minimize
from cirq_web import bloch_sphere
from cirq import Z, PauliSum

import sys
sys.meta_path[:] = [f for f in sys.meta_path if "DaskFinder" not in str(f)]

def create_ghz_circuit(alice_basis, bob_basis, charlie_basis, eve_interferes=False, eve_apply_x_gate_probability=1.0):
    """
    Creates a 3-qubit GHZ state and measures it based on chosen bases.
    Bases: 'Z' = Standard measurement, 'X' = Diagonal measurement

    If eve_interferes is True, Eve measures Bob's qubit in the Z-basis. If
    random.random() < eve_apply_x_gate_probability, Eve also applies an X gate,
    causing a bit flip relative to Alice and Charlie's results when all measure
    in the Z-basis. This action is designed to be detectable.
    """
    # Define three qubits for Alice, Bob, and Charlie
    q = cirq.NamedQubit.range(3, prefix='q')
    circuit = cirq.Circuit()

    # 1. State Preparation: Create the entangled GHZ State (|000> + |111>) / sqrt(2)
    circuit.append([
        cirq.H(q[0]),          # Put Alice in superposition
        cirq.CNOT(q[0], q[1]),    # Entangle Bob with Alice
        cirq.CNOT(q[1], q[2])     # Entangle Charlie with Bob
    ])

    # 2. Optional Eavesdropping Simulation
    if eve_interferes:
        # Eve secretly measures Bob's qubit in the Z-basis to gain information.
        # This measurement collapses the superposition.
        circuit.append(cirq.measure(q[1], key='eve_measurement'))

        # Based on eve_apply_x_gate_probability, Eve may or may not apply an X gate.
        # Applying an X gate (bit flip) guarantees a discrepancy if A, B, C measure in Z.
        if random.random() < eve_apply_x_gate_probability:
            circuit.append(cirq.X(q[1])) # Apply X gate (bit flip) to simulate Eve's effect

    # 3. Measurement Basis Changes
    # If a party chooses the X-basis, we apply a Hadamard gate before measuring
    if alice_basis == 'X': circuit.append(cirq.H(q[0]))
    if bob_basis == 'X': circuit.append(cirq.H(q[1]))
    if charlie_basis == 'X': circuit.append(cirq.H(q[2]))

    # 4. Final Measurement
    circuit.append([
        cirq.measure(q[0], key='Alice'),
        cirq.measure(q[1], key='Bob'),
        cirq.measure(q[2], key='Charlie')
    ])

    return circuit

def run_simulation(num_bits, eavesdropper_present, eve_attack_probability=0.5, eve_apply_x_gate_probability=1.0):
    simulator = cirq.Simulator()

    all_alice_results = []
    all_bob_results = []
    all_charlie_results = []
    all_alice_bases = []
    all_bob_bases = []
    all_charlie_bases = []

    for _ in range(num_bits):
        # Randomly choose Z or X basis for all three parties
        a_basis = random.choice(['Z', 'X'])
        b_basis = random.choice(['Z', 'X'])
        c_basis = random.choice(['Z', 'X'])

        # Determine if Eve interferes for *this specific bit*.
        # Eve only interferes with a certain probability per bit if she's present.
        eve_interferes_this_bit = False
        if eavesdropper_present:
            if random.random() < eve_attack_probability:
                eve_interferes_this_bit = True

        # Build and simulate the circuit for this single bit
        circuit = create_ghz_circuit(a_basis, b_basis, c_basis,
                                     eve_interferes=eve_interferes_this_bit,
                                     eve_apply_x_gate_probability=eve_apply_x_gate_probability)
        result = simulator.run(circuit, repetitions=1) # Run for 1 repetition to get a single bit

        # Extract the results (0 or 1)
        a_res = result.measurements['Alice'][0][0]
        b_res = result.measurements['Bob'][0][0]
        c_res = result.measurements['Charlie'][0][0]

        # Collect all results and bases
        all_alice_results.append(a_res)
        all_bob_results.append(b_res)
        all_charlie_results.append(c_res)
        all_alice_bases.append(a_basis)
        all_bob_bases.append(b_basis)
        all_charlie_bases.append(c_basis)

    # Return all results and bases for later analysis
    return all_alice_results, all_bob_results, all_charlie_results, \
           all_alice_bases, all_bob_bases, all_charlie_bases

def analyze_qkd_results(alice_results, bob_results, charlie_results,
                        alice_bases, bob_bases, charlie_bases):
    """
    Analyzes the full QKD simulation results for signs of eavesdropping.
    Checks for consistency in both ZZZ and XXX basis measurements.
    """
    # 1. Z-Basis Consistency Check (Expected: A=B=C for secure communication)
    zzz_alice_key = []
    zzz_bob_key = []
    zzz_charlie_key = []

    for i in range(len(alice_bases)):
        if (alice_bases[i] == 'Z' and
            bob_bases[i] == 'Z' and
            charlie_bases[i] == 'Z'):
            zzz_alice_key.append(alice_results[i])
            zzz_bob_key.append(bob_results[i])
            zzz_charlie_key.append(charlie_results[i])

    zzz_discrepancies = 0
    if len(zzz_alice_key) > 0:
        for i in range(len(zzz_alice_key)):
            if not (zzz_alice_key[i] == zzz_bob_key[i] == zzz_charlie_key[i]):
                zzz_discrepancies += 1

    # 2. X-Basis Consistency Check (Expected: A=B=C for secure communication with GHZ)
    xxx_alice_key = []
    xxx_bob_key = []
    xxx_charlie_key = []

    for i in range(len(alice_bases)):
        if (alice_bases[i] == 'X' and
            bob_bases[i] == 'X' and
            charlie_bases[i] == 'X'):
            xxx_alice_key.append(alice_results[i])
            xxx_bob_key.append(bob_results[i])
            xxx_charlie_key.append(charlie_results[i])

    xxx_discrepancies = 0
    if len(xxx_alice_key) > 0:
        for i in range(len(xxx_alice_key)):
            if not (xxx_alice_key[i] == xxx_bob_key[i] == xxx_charlie_key[i]):
                xxx_discrepancies += 1

    detection_messages = []

    if len(zzz_alice_key) > 0:
        if zzz_discrepancies > 0:
            detection_messages.append(
                f"ZZZ Basis Check: Eavesdropper DETECTED! {zzz_discrepancies} discrepancies found out of {len(zzz_alice_key)} ZZZ-bits."
            )
        else:
            detection_messages.append(
                f"ZZZ Basis Check: No eavesdropper detected. {len(zzz_alice_key)} ZZZ-bits match perfectly."
            )
    else:
        detection_messages.append(
            "ZZZ Basis Check: Not enough ZZZ-bits for a reliable check."
        )

    if len(xxx_alice_key) > 0:
        if xxx_discrepancies > 0:
            detection_messages.append(
                f"XXX Basis Check: Eavesdropper DETECTED! {xxx_discrepancies} discrepancies found out of {len(xxx_alice_key)} XXX-bits. (Eve's measurement broke X-correlations)"
            )
        else:
            detection_messages.append(
                f"XXX Basis Check: No eavesdropper detected. {len(xxx_alice_key)} XXX-bits match perfectly."
            )
    else:
        detection_messages.append(
            "XXX Basis Check: Not enough XXX-bits for a reliable check."
        )

    if zzz_discrepancies > 0 or xxx_discrepancies > 0:
        overall_status = "Overall: Eavesdropper DETECTED!"
    else:
        overall_status = "Overall: No eavesdropper detected."

    return "\n".join(detection_messages) + f"\n\n{overall_status}"

# --- Eavesdropped Scenario --- (Eve measures, but DOES NOT apply X-gate)
num_bits = 1000 # Number of bits to simulate
eve_attack_probability = 1.0 # Eve attempts to measure every bit
eve_apply_x_gate_probability = 0.0 # Eve measures, but NEVER applies an X gate

print("\n--- Running EAVESDROPPED GHZ QKD Simulation (Eve measures, no X-gate) ---\n")
alice_results, bob_results, charlie_results, \
alice_bases, bob_bases, charlie_bases = run_simulation(
    num_bits,
    eavesdropper_present=True,
    eve_attack_probability=eve_attack_probability,
    eve_apply_x_gate_probability=eve_apply_x_gate_probability
)

print(f"Eve's measurement probability per bit: {eve_attack_probability*100}% (meaning she tries to 'eavesdrop' on all bits)\n")
print(f"Eve's bit-flip (X-gate) application probability after measurement: {eve_apply_x_gate_probability*100}% (meaning she never applies an X-gate)\n")

print(f"Total simulated bits: {num_bits}")
print(f"Alice's first 20 results: {alice_results[:20]}...")
print(f"Bob's first 20 results:   {bob_results[:20]}...")
print(f"Charlie's first 20 results: {charlie_results[:20]}...")

# Analyze the collected results and bases
analysis_results = analyze_qkd_results(
    alice_results, bob_results, charlie_results,
    alice_bases, bob_bases, charlie_bases
)
print(f"\nSecurity Analysis Results:\n{analysis_results}")