# -*- coding: utf-8 -*-
"""Quantum Coinflip

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11QX0RPakxGZDjGhE9Bs-UzPytOlcHT1a
"""

!pip install cirq --quiet
import cirq

def QuantumCoinflip():

    qubit = cirq.NamedQubit('x')
    circuit = cirq.Circuit()
    circuit.append(cirq.H(qubit))
    circuit.append(cirq.measure(qubit))
    sim = cirq.Simulator()
    output = sim.run(circuit, repetitions=200)
    print(circuit)
    output
    return output 
